#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mistune
Version  : 0.7.3
Release  : 1
URL      : https://pypi.python.org/packages/88/1e/be99791262b3a794332fda598a07c2749a433b9378586361ba9d8e824607/mistune-0.7.3.tar.gz
Source0  : https://pypi.python.org/packages/88/1e/be99791262b3a794332fda598a07c2749a433b9378586361ba9d8e824607/mistune-0.7.3.tar.gz
Summary  : The fastest markdown parser in pure Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mistune-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Mistune
=======
The fastest markdown parser in pure Python with renderer features,
inspired by marked_.

%package python
Summary: python components for the mistune package.
Group: Default

%description python
python components for the mistune package.


%prep
%setup -q -n mistune-0.7.3

%build
export LANG=C
export SOURCE_DATE_EPOCH=1486352045
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1486352045
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
