#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mistune
Version  : 0.7.4
Release  : 3
URL      : http://pypi.debian.net/mistune/mistune-0.7.4.tar.gz
Source0  : http://pypi.debian.net/mistune/mistune-0.7.4.tar.gz
Summary  : The fastest markdown parser in pure Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mistune-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Mistune
=======
The fastest markdown parser in pure Python with renderer features,
inspired by marked_.

%package python
Summary: python components for the mistune package.
Group: Default

%description python
python components for the mistune package.


%prep
%setup -q -n mistune-0.7.4

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489774005
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.6/site-packages python3 setup.py test
%install
export SOURCE_DATE_EPOCH=1489774005
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
